# Generated by Django 4.2.14 on 2024-08-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('class_type', models.CharField(choices=[('crop', 'Crop'), ('livestock', 'Livestock')], max_length=10)),
            ],
        ),
    ]
