# Generated by Django 4.2.14 on 2024-08-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='details',
            new_name='detail',
        ),
    ]
